name: tklocation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  firebase_core: any
  firebase_database: any
  firebase_auth: any
  intl: ^0.17.0
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  tklogger:
    git:
      url: https://github.com/timmkent/tklogger.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true