name: tklocation
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.0
  firebase_database: ^10.3.6
  firebase_auth: ^4.15.0
  intl: ^0.18.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  tklogger:
    git:
      url: https://github.com/timmkent/tklogger.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true